// export const themes = [
// 	"light",
// 	"dark",
// 	"cupcake",
// 	"bumblebee",
// 	"emerald",
// 	"corporate",
// 	"synthwave",
// 	"retro",
// 	"cyberpunk",
// 	"valentine",
// 	"halloween",
// 	"garden",
// 	"forest",
// 	"aqua",
// 	"lofi",
// 	"pastel",
// 	"fantasy",
// 	"wireframe",
// 	"black",
// 	"luxury",
// 	"dracula",
// 	"cmyk",
// 	"autumn",
// 	"business",
// 	"acid",
// 	"lemonade",
// 	"night",
// 	"coffee",
// 	"winter"
// ];

export const themes = [
	{ title: "Light (default)", theme: "light" },
	{ title: "Dark (default)", theme: "dark" },
	{ title: "Cupcake (light)", theme: "cupcake" },
	{ title: "Bumblebee (light)", theme: "bumblebee" },
	{ title: "Emerald (light)", theme: "emerald" },
	{ title: "Corporate (light)", theme: "corporate" },
	{ title: "Garden (light)", theme: "garden" },
	{ title: "Lofi (light)", theme: "lofi" },
	{ title: "Pastel (light)", theme: "pastel" },
	{ title: "Fantasy (light)", theme: "fantasy" },
	{ title: "Wireframe (light)", theme: "wireframe" },
	{ title: "CMYK (light)", theme: "cmyk" },
	{ title: "Autumn (light)", theme: "autumn" },
	{ title: "Acid (light)", theme: "acid" },
	{ title: "Lemonade (light)", theme: "lemonade" },
	{ title: "Winter (light)", theme: "winter" },
	{ title: "Synthwave (dark)", theme: "synthwave" },
	{ title: "Halloween (dark)", theme: "halloween" },
	{ title: "Forest (dark)", theme: "forest" },
	{ title: "Black (dark)", theme: "black" },
	{ title: "Luxury (dark)", theme: "luxury" },
	{ title: "Dracula (dark)", theme: "dracula" },
	{ title: "Business (dark)", theme: "business" },
	{ title: "Night (dark)", theme: "night" },
	{ title: "Coffee (dark)", theme: "coffee" },
	{ title: "Retro (color)", theme: "retro" },
	{ title: "Cyberpunk (color)", theme: "cyberpunk" },
	{ title: "Valentine (color)", theme: "valentine" },
	{ title: "Aqua (color)", theme: "aqua" }
];
